name: Android Kernel CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex build-essential libssl-dev \
          libncurses5-dev lz4 liblz4-tool python-is-python3 zip \
          libelf-dev libncurses-dev ccache clang lld libc++-dev

    - name: Clone toolchain
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang

    - name: Kernel config
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH=$PWD/clang/bin:$PATH
        make O=out YOUR_DEFCONFIG

    - name: Build kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH=$PWD/clang/bin:$PATH
        make O=out -j$(nproc) CC=clang

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-out
        path: out/arch/arm64/boot/
